Repository trustbloc/agent-sdk, pull requests merged in 2020-10, with the labels that each got.

#1 feat: WASM build based on edge-agent
  .github/workflows/build.yml
  .gitignore
  cmd/agent-js-worker/.gitignore
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/main.go
  cmd/agent-js-worker/main_test.go
  cmd/agent-js-worker/package-lock.json
  cmd/agent-js-worker/package.json
  cmd/agent-js-worker/scripts/build_assets.sh
  cmd/agent-js-worker/src/agent.js
  cmd/agent-js-worker/src/wasm_exec.js
  cmd/agent-js-worker/src/worker-impl-web.js
  cmd/agent-js-worker/src/worker-loader-web.js
  cmd/agent-js-worker/webpack.config.common.js
  cmd/agent-js-worker/webpack.config.web.js
  go.mod
  go.sum
  pkg/controller/command/api.go
  pkg/controller/command/credentialclient/command.go
  pkg/controller/command/credentialclient/command_test.go
  pkg/controller/command/didclient/command.go
  pkg/controller/command/didclient/command_test.go
  pkg/controller/command/didclient/models.go
  pkg/controller/command/errors.go
  pkg/controller/command/errors_test.go
  pkg/controller/command/internal/cmdutil/handler.go
  pkg/controller/command/internal/cmdutil/handler_test.go
  pkg/controller/command/internal/logutil/util.go
  pkg/controller/command/presentationclient/command.go
  pkg/controller/command/presentationclient/command_test.go
  pkg/controller/command/sdscomm/messages.go
  pkg/controller/command/sdscomm/models.go
  pkg/controller/command/sdscomm/sdscomm.go
  pkg/controller/command/sdscomm/sdscomm_test.go
  pkg/controller/command/util.go
  pkg/controller/command/util_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: cla-signed

#2 fix: Fixes github actions
  .github/workflows/build.yml
Labels: cla-signed

#4 ci: Added azure
  .github/workflows/build.yml
  .gitignore
  Makefile
  ci/azp-dependencies.yml
  ci/azure-pipelines.yml
  scripts/check_license.sh
  scripts/check_lint.sh
  scripts/check_unit.sh
  scripts/check_unit_wasm.sh
Labels: cla-signed

#5 ci: JS publish npm package
  ci/azure-pipelines.yml
Labels: cla-signed

#6 ci: JS publish npm package
  ci/azure-pipelines.yml
  ci/version_var.sh
  cmd/agent-js-worker/package.json
Labels: cla-signed

#7 feat: Adds trustbloc-did-method support (wasm)
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/main.go
  cmd/agent-js-worker/main_test.go
  cmd/agent-js-worker/src/agent.js
Labels: cla-signed, wip

#10 feat: create peer DID command in didclient
  cmd/agent-js-worker/main.go
  cmd/agent-js-worker/src/agent.js
  pkg/controller/command/didclient/command.go
  pkg/controller/command/didclient/command_test.go
  pkg/controller/command/didclient/models.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
Labels: cla-signed

#13 chore: renaming createBlocDID to createTrustBlocDID
  cmd/agent-js-worker/src/agent.js
  pkg/controller/command/didclient/command.go
  pkg/controller/command/didclient/command_test.go
Labels: cla-signed

#14 ci: Fixes docker publish job
  Makefile
  ci/azure-pipelines.yml
Labels: cla-signed

#15 ci: Fixes docker publish job
  Makefile
  ci/azure-pipelines.yml
  ci/version_var.sh
Labels: cla-signed

#16 ci: Fixes docker publish job
  ci/azure-pipelines.yml
Labels: cla-signed

#17 fix: typo in create trustbloc did command name
  cmd/agent-js-worker/src/agent.js
  pkg/controller/command/didclient/command.go
Labels: cla-signed

#19 feat: Adds Couchdb and MySQL support (rest docker image)
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  cmd/agent-rest/startcmd/start.go
  cmd/agent-rest/startcmd/start_test.go
  go.mod
  go.sum
Labels: cla-signed

#20 feat: Adds trustbloc-did-method support (docker rest)
  cmd/agent-js-worker/main.go
  cmd/agent-js-worker/main_test.go
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  cmd/agent-rest/startcmd/start.go
  cmd/agent-rest/startcmd/start_test.go
  go.mod
  go.sum
  scripts/check_lint.sh
Labels: cla-signed

#21 fix: Keeps resolvers initial order
  cmd/agent-js-worker/main.go
  cmd/agent-rest/startcmd/start.go
Labels: bug, cla-signed

#26 chore: update aries-framework-go revision
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed
