Repository trustbloc/agent-sdk, pull requests merged in 2020-11, with the labels that each got.

#27 feat: Adds trustbloc did method support for mobile
  README.md
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-mobile/pkg/wrappers/command/aries.go
  cmd/agent-mobile/pkg/wrappers/command/aries_test.go
  cmd/agent-mobile/pkg/wrappers/config/options.go
Labels: cla-signed

#28 feat: Adds the possibility to create Trustbloc/Peer DIDs
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-mobile/pkg/api/api.go
  cmd/agent-mobile/pkg/api/didclient.go
  cmd/agent-mobile/pkg/wrappers/command/aries.go
  cmd/agent-mobile/pkg/wrappers/command/didclient.go
  cmd/agent-mobile/pkg/wrappers/command/didclient_test.go
  cmd/agent-mobile/pkg/wrappers/rest/aries.go
  pkg/controller/command/didclient/command.go
  pkg/controller/command/util.go
  pkg/controller/command/util_test.go
Labels: cla-signed

#29 feat: Adds the possibility to create Trustbloc/Peer DIDs (docker)
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  cmd/agent-rest/startcmd/start.go
  pkg/controller/command/credentialclient/command.go
  pkg/controller/command/didclient/command.go
  pkg/controller/command/didclient/command_test.go
  pkg/controller/command/errors.go
  pkg/controller/command/presentationclient/command.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/internal/cmdutil/handler.go
  pkg/controller/internal/cmdutil/handler_test.go
  pkg/controller/internal/logutil/util.go
  pkg/controller/rest/didclient/operation.go
  pkg/controller/rest/rest.go
  pkg/controller/rest/rest_test.go
Labels: cla-signed, wip

#31 chore: update sidetree, did-method
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
  pkg/controller/command/didclient/command.go
  pkg/controller/command/didclient/models.go
Labels: cla-signed

#33 chore: rename 'purpose' to 'purposes'
  pkg/controller/command/didclient/models.go
Labels: cla-signed

#35 chore: update did-method
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#36 feat: Adds the possibility to create Trustbloc/Peer DIDs (mobile rest)
  cmd/agent-mobile/pkg/wrappers/rest/aries.go
  cmd/agent-mobile/pkg/wrappers/rest/didclient.go
  cmd/agent-mobile/pkg/wrappers/rest/didclient_test.go
  cmd/agent-mobile/pkg/wrappers/rest/endpoints.go
  cmd/agent-mobile/pkg/wrappers/rest/kms.go
Labels: cla-signed

#37 refactor: Replaces Bloc with TrustBloc
  cmd/agent-mobile/pkg/wrappers/command/didclient.go
  cmd/agent-mobile/pkg/wrappers/command/didclient_test.go
  cmd/agent-mobile/pkg/wrappers/rest/didclient.go
  cmd/agent-mobile/pkg/wrappers/rest/endpoints.go
  pkg/controller/command/didclient/command.go
  pkg/controller/command/didclient/command_test.go
Labels: cla-signed

#38 chore: update trustbloc-did-revision
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
  pkg/controller/command/didclient/command.go
  pkg/controller/command/didclient/command_test.go
Labels: cla-signed

#39 feat: REST SDK support for js.
  cmd/agent-js-worker/package-lock.json
  cmd/agent-js-worker/package.json
  cmd/agent-js-worker/rest.js
  cmd/agent-js-worker/src/agent-rest-client.js
  cmd/agent-js-worker/src/worker-impl-rest.js
  cmd/agent-js-worker/src/worker-loader-rest.js
  cmd/agent-js-worker/webpack.config.rest.js
Labels: cla-signed

#40 feat: DIDClient REST support (JS)
  cmd/agent-js-worker/src/agent-rest-client.js
Labels: cla-signed

#42 feat: Credential/Presentation clients support
  cmd/agent-js-worker/src/agent-rest-client.js
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-mobile/pkg/api/api.go
  cmd/agent-mobile/pkg/api/credentialclient.go
  cmd/agent-mobile/pkg/api/presentationclient.go
  cmd/agent-mobile/pkg/wrappers/command/aries.go
  cmd/agent-mobile/pkg/wrappers/command/credentialclient.go
  cmd/agent-mobile/pkg/wrappers/command/credentialclient_test.go
  cmd/agent-mobile/pkg/wrappers/command/presentationclient.go
  cmd/agent-mobile/pkg/wrappers/command/presentationclient_test.go
  cmd/agent-mobile/pkg/wrappers/rest/aries.go
  cmd/agent-mobile/pkg/wrappers/rest/credentialclient.go
  cmd/agent-mobile/pkg/wrappers/rest/credentialclient_test.go
  cmd/agent-mobile/pkg/wrappers/rest/endpoints.go
  cmd/agent-mobile/pkg/wrappers/rest/presentationclient.go
  cmd/agent-mobile/pkg/wrappers/rest/presentationclient_test.go
  pkg/controller/command/credentialclient/command.go
  pkg/controller/command/presentationclient/command.go
  pkg/controller/controller.go
  pkg/controller/rest/credentialclient/operation.go
  pkg/controller/rest/credentialclient/operation_test.go
  pkg/controller/rest/presentationclient/operation.go
  pkg/controller/rest/presentationclient/operation_test.go
Labels: cla-signed

#46 docs: Adds mobile docs
  cmd/agent-mobile/README.md
  cmd/agent-mobile/doc/project_structure.md
Labels: cla-signed

#41 feat: Initial Aries EDV provider integration
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/main.go
  cmd/agent-js-worker/src/agent-rest-client.js
  cmd/agent-js-worker/src/agent.js
  cmd/agent-mobile/pkg/api/api.go
  cmd/agent-mobile/pkg/api/credentialclient.go
  cmd/agent-mobile/pkg/api/presentationclient.go
  cmd/agent-mobile/pkg/wrappers/command/aries.go
  cmd/agent-mobile/pkg/wrappers/command/credentialclient.go
  cmd/agent-mobile/pkg/wrappers/command/credentialclient_test.go
  cmd/agent-mobile/pkg/wrappers/command/presentationclient.go
  cmd/agent-mobile/pkg/wrappers/command/presentationclient_test.go
  cmd/agent-mobile/pkg/wrappers/rest/aries.go
  cmd/agent-mobile/pkg/wrappers/rest/credentialclient.go
  cmd/agent-mobile/pkg/wrappers/rest/credentialclient_test.go
  cmd/agent-mobile/pkg/wrappers/rest/endpoints.go
  cmd/agent-mobile/pkg/wrappers/rest/presentationclient.go
  cmd/agent-mobile/pkg/wrappers/rest/presentationclient_test.go
  cmd/agent-rest/startcmd/start.go
  pkg/controller/command/credentialclient/command.go
  pkg/controller/command/credentialclient/command_test.go
  pkg/controller/command/didclient/command.go
  pkg/controller/command/didclient/command_test.go
  pkg/controller/command/presentationclient/command.go
  pkg/controller/command/presentationclient/command_test.go
  pkg/controller/command/sdscomm/messages.go
  pkg/controller/command/sdscomm/models.go
  pkg/controller/command/sdscomm/sdscomm.go
  pkg/controller/command/sdscomm/sdscomm_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/rest/credentialclient/operation.go
  pkg/controller/rest/credentialclient/operation_test.go
  pkg/controller/rest/didclient/operation.go
  pkg/controller/rest/presentationclient/operation.go
  pkg/controller/rest/presentationclient/operation_test.go
Labels: cla-signed

#49 feat: Adds the possibility to inject storage (mobile)
  cmd/agent-mobile/pkg/api/storage.go
  cmd/agent-mobile/pkg/wrappers/command/aries.go
  cmd/agent-mobile/pkg/wrappers/config/options.go
  cmd/agent-mobile/pkg/wrappers/storage/storage.go
  cmd/agent-mobile/pkg/wrappers/storage/storage_test.go
Labels: cla-signed

#50 fix: Unit test coverage file doesn't include agent-sdk folder
  scripts/check_unit.sh
Labels: cla-signed

#51 feat: Adds OpenAPI spec
  .gitignore
  Makefile
  cmd/agent-rest/main.go
  cmd/agent-rest/startcmd/start.go
  cmd/agent-rest/startcmd/start_test.go
  deployments/agent-rest/.env
  deployments/agent-rest/docker-compose.yml
  deployments/demo/openapi/.env
  deployments/demo/openapi/docker-compose.yml
  deployments/sidetree-mock/.env
  deployments/sidetree-mock/docker-compose.yml
  pkg/controller/rest/didclient/models.go
  pkg/controller/rest/didclient/operation.go
  pkg/controller/rest/rest.go
  scripts/generate-openapi-demo-specs.sh
  scripts/generate-openapi-spec.sh
  scripts/generate_test_keys.sh
  scripts/run-openapi-demo.sh
Labels: cla-signed

#52 chore: update aries-framework-go and did-method revision
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/main.go
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
  pkg/controller/command/didclient/command.go
  pkg/controller/command/didclient/command_test.go
Labels: cla-signed

#53 feat: Adds REST API bdd tests
  Makefile
  ci/azure-pipelines.yml
  deployments/agent-rest/docker-compose.yml
  deployments/sidetree-mock/docker-compose.yml
  scripts/aries_bdd_tests.sh
Labels: cla-signed

#54 chore: update trustbloc-did-method
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#58 feat: mediatorclient command controller with connect command
  cmd/agent-js-worker/src/agent-rest-client.js
  cmd/agent-js-worker/src/agent.js
  pkg/controller/command/errors.go
  pkg/controller/command/mediatorclient/command.go
  pkg/controller/command/mediatorclient/command_test.go
  pkg/controller/command/mediatorclient/models.go
  pkg/controller/controller.go
  pkg/controller/internal/mocks/protocol/didexchange.go
  pkg/controller/internal/mocks/protocol/outofband.go
  pkg/controller/internal/testutil/testutil.go
  pkg/controller/rest/mediatorclient/models.go
  pkg/controller/rest/mediatorclient/operation.go
  pkg/controller/rest/mediatorclient/operation_test.go
Labels: cla-signed

#55 test: Adds JS bdd tests based on Aries
  Makefile
  ci/azure-pipelines.yml
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/src/agent.js
  scripts/aries_bdd_tests.sh
  scripts/aries_js_bdd_tests.sh
Labels: cla-signed

#59 chore: update trustbloc-did-method revision
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#60 ci: Adds dependencies for Publish job
  ci/azure-pipelines.yml
Labels: cla-signed

#61 fix: Maps custom error to storage error (mobile)
  cmd/agent-mobile/pkg/wrappers/storage/storage.go
Labels: cla-signed

#62 feat: state complete message check for mediator connect
  cmd/agent-rest/startcmd/start.go
  pkg/controller/command/mediatorclient/command.go
  pkg/controller/command/mediatorclient/command_test.go
  pkg/controller/command/mediatorclient/models.go
  pkg/controller/controller.go
  pkg/controller/internal/msghandler/messagesvc.go
  pkg/controller/internal/msghandler/notifier.go
  pkg/controller/rest/mediatorclient/operation.go
  pkg/controller/rest/mediatorclient/operation_test.go
Labels: cla-signed

#64 docs: Adds documentation for agent js
  cmd/agent-js-worker/README.md
Labels: cla-signed

#65 feat: mediator reconnect all & create invitation
  cmd/agent-js-worker/src/agent-rest-client.js
  cmd/agent-js-worker/src/agent.js
  pkg/controller/command/mediatorclient/command.go
  pkg/controller/command/mediatorclient/command_test.go
  pkg/controller/command/mediatorclient/models.go
  pkg/controller/command/registry.go
  pkg/controller/command/registry_test.go
  pkg/controller/controller.go
  pkg/controller/internal/mocks/protocol/outofband.go
  pkg/controller/rest/mediatorclient/models.go
  pkg/controller/rest/mediatorclient/operation.go
  pkg/controller/rest/mediatorclient/operation_test.go
Labels: cla-signed

#66 docs: Adds links to the README (bindings)
  Makefile
  README.md
  docs/test/build.md
Labels: cla-signed

#68 feat: Updated EDV storage implementation
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/main.go
  cmd/agent-js-worker/src/agent.js
  cmd/agent-mobile/pkg/wrappers/command/aries.go
  cmd/agent-rest/startcmd/start.go
  docs/rest/agent_cli.md
Labels: cla-signed

#70 feat: Update aries-framework-go dependency
  Makefile
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#71 feat: Update aries-framework-go dependency
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#72 feat: using messenger in mediator client
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/src/agent-rest-client.js
  cmd/agent-js-worker/src/agent.js
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
  pkg/controller/command/mediatorclient/command.go
  pkg/controller/command/mediatorclient/command_test.go
  pkg/controller/controller.go
  pkg/controller/controller_test.go
  pkg/controller/internal/mocks/mock_webhook.go
  pkg/controller/internal/mocks/protocol/provider.go
  pkg/controller/internal/msghandler/notifier.go
  pkg/controller/rest/mediatorclient/operation.go
  pkg/controller/rest/mediatorclient/operation_test.go
Labels: cla-signed

#73 feat: send create connection request
  pkg/controller/command/mediatorclient/command.go
  pkg/controller/command/mediatorclient/command_test.go
  pkg/controller/command/mediatorclient/models.go
  pkg/controller/command/registry.go
  pkg/controller/command/registry_test.go
  pkg/controller/internal/mocks/protocol/provider.go
  pkg/controller/rest/mediatorclient/models.go
  pkg/controller/rest/mediatorclient/operation.go
  pkg/controller/rest/mediatorclient/operation_test.go
Labels: cla-signed

#75 feat: blinded routing command features
  cmd/agent-js-worker/src/agent-rest-client.js
  cmd/agent-js-worker/src/agent.js
  pkg/controller/command/blindedrouting/command.go
  pkg/controller/command/blindedrouting/command_test.go
  pkg/controller/command/blindedrouting/models.go
  pkg/controller/command/mediatorclient/command.go
  pkg/controller/command/mediatorclient/command_test.go
  pkg/controller/command/mediatorclient/models.go
  pkg/controller/controller.go
  pkg/controller/internal/mocks/protocol/provider.go
  pkg/controller/rest/blindedrouting/models.go
  pkg/controller/rest/blindedrouting/operation.go
  pkg/controller/rest/blindedrouting/operation_test.go
  pkg/controller/rest/mediatorclient/operation.go
  pkg/controller/rest/mediatorclient/operation_test.go
Labels: cla-signed

#76 chore: update to latest aries-framework-go commit
  Makefile
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: chore, cla-signed

#80 fix: agent-sdk JS integration issues
  cmd/agent-js-worker/main.go
  cmd/agent-js-worker/src/agent.js
Labels: cla-signed

#83 chore: update to latest aries
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#82 feat: add edv zcap
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/main.go
  cmd/agent-js-worker/package.json
  go.mod
  go.sum
  pkg/auth/zcapld/service.go
  pkg/auth/zcapld/service_test.go
Labels: cla-signed

#85 fix: Missing key ID
  cmd/agent-js-worker/main.go
  cmd/agent-js-worker/src/agent.js
  pkg/controller/command/mediatorclient/command.go
Labels: cla-signed

#86 refactor: split kms from edv creation
  Makefile
  cmd/agent-js-worker/main.go
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.sum
Labels: cla-signed

#87 fix: Revert echoTimeout change
  cmd/agent-js-worker/main.go
Labels: cla-signed

#88 feat: add support for remoteKMS/Crypto
  cmd/agent-js-worker/main.go
Labels: cla-signed

#91 feat: Support to pass userHalfSecret and sub in header to authz kms
  cmd/agent-js-worker/main.go
  pkg/auth/zcapld/service.go
  pkg/auth/zcapld/service_test.go
Labels: cla-signed

#90 feat: complete remoteKMS/remoteCrypto in agent-js-worker
  cmd/agent-js-worker/main.go
Labels: cla-signed

#92 feat: add edv caching
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/main.go
  go.mod
  go.sum
  pkg/storage/jsindexeddbcache/db.go
  pkg/storage/jsindexeddbcache/db_test.go
  scripts/check_unit_wasm.sh
Labels: cla-signed

#93 fix: remove clear cache when open store
  pkg/storage/jsindexeddbcache/db.go
  pkg/storage/jsindexeddbcache/db_test.go
Labels: cla-signed

#96 refactor: #94 make zcapld.Service.SignHeader() accept invocation action
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/main.go
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
  pkg/auth/zcapld/service.go
  pkg/auth/zcapld/service_test.go
Labels: cla-signed, refactor

#95 fix: remove clear cache when open store
  pkg/storage/jsindexeddbcache/db.go
Labels: cla-signed

#97 chore: Updates Aries version
  Makefile
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/Makefile
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#98 feat: Update Aries and enable EDV provider query optimization
  Makefile
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/main.go
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#100 refactor: replace useRemoteKMS with KMSType in agent options
  cmd/agent-js-worker/main.go
Labels: cla-signed

#101 chore: update latest aries-framework-go
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#102 chore: Updates Aries revision
  Makefile
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed
