Repository trustbloc/agent-sdk, pull requests merged in 2021-03, with the labels that each got.

#152 fix: storage errors when using IndexedDB-only option in agent-js-worker
  Makefile
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  go.mod
  go.sum
  pkg/storage/jsindexeddbcache/db.go
Labels: cla-signed

#153 chore: update to latest aries
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/src/agent-rest-client.js
  cmd/agent-js-worker/src/agent.js
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#154 chore: upgrade afg
  Makefile
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#155 chore: updated aries framework go version
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#156 chore: use aries did key resolver
  cmd/agent-js-worker/main.go
Labels: cla-signed

#157 chore: update trustbloc-did-method
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/main.go
  cmd/agent-js-worker/main_test.go
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-mobile/pkg/wrappers/command/aries.go
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  cmd/agent-rest/startcmd/start.go
  deployments/sidetree-mock/.env
  go.mod
  go.sum
  pkg/controller/command/didclient/command.go
Labels: cla-signed

#160 feat: Re-add LevelDB and MySQL options to agent-rest
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  cmd/agent-rest/startcmd/start.go
  cmd/agent-rest/startcmd/start_test.go
  deployments/agent-rest/docker-compose.yml
  docs/rest/agent_cli.md
Labels: cla-signed

#162 chore: Update aries-framework-go-ext commit versions
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#164 chore: Updates Aries
  Makefile
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#165 chore: Release v0.1.6
  Makefile
  ci/version_var.sh
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  deployments/agent-rest/.env
  deployments/sidetree-mock/.env
  go.mod
  go.sum
Labels: cla-signed

#167 chore: Bump version to 0.1.7
  ci/version_var.sh
Labels: cla-signed

#168 chore: Updates Aries revision
  Makefile
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#169 chore: use different name for cicd package name
  ci/version_var.sh
Labels: cla-signed

#170 chore: Updates Aries revision
  Makefile
  ci/azure-pipelines.yml
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#171 chore: update AFGO
  Makefile
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: chore, cla-signed

#172 chore: rename npm package to agent-sdk-web
  ci/azure-pipelines.yml
  ci/version_var.sh
  cmd/agent-js-worker/package.json
Labels: cla-signed

#173 fix: npm package in publish script
  ci/version_var.sh
Labels: cla-signed

#174 fix: return discoverable did trustbloc
  pkg/controller/command/didclient/command.go
  pkg/controller/command/didclient/command_test.go
Labels: cla-signed

#186 chore: Updates AFG version
  Makefile
  cmd/agent-js-worker/README.md
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/main.go
  cmd/agent-js-worker/src/agent-rest-client.js
  cmd/agent-js-worker/src/agent.js
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
  scripts/aries_js_bdd_tests.sh
Labels: cla-signed

#187 chore: Updates AFG version
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/main.go
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.sum
  go.sum
Labels: cla-signed

#188 chore: update AFGO - delete outofband.Request
  Makefile
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/package-lock.json
  cmd/agent-js-worker/src/agent-rest-client.js
  cmd/agent-js-worker/src/agent.js
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-mobile/pkg/api/introduce.go
  cmd/agent-mobile/pkg/api/mediator.go
  cmd/agent-mobile/pkg/api/outofband.go
  cmd/agent-mobile/pkg/wrappers/command/introduce.go
  cmd/agent-mobile/pkg/wrappers/command/introduce_test.go
  cmd/agent-mobile/pkg/wrappers/command/outofband.go
  cmd/agent-mobile/pkg/wrappers/command/outofband_test.go
  cmd/agent-mobile/pkg/wrappers/rest/endpoints.go
  cmd/agent-mobile/pkg/wrappers/rest/introduce.go
  cmd/agent-mobile/pkg/wrappers/rest/introduce_test.go
  cmd/agent-mobile/pkg/wrappers/rest/mediator.go
  cmd/agent-mobile/pkg/wrappers/rest/outofband.go
  cmd/agent-mobile/pkg/wrappers/rest/outofband_test.go
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
  pkg/controller/command/mediatorclient/command.go
  pkg/controller/internal/mocks/protocol/outofband.go
Labels: chore, cla-signed

#189 chore: update AFGO
  Makefile
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
  pkg/controller/command/didclient/command.go
  pkg/controller/command/didclient/command_test.go
Labels: chore, cla-signed

#190 fix: "CreatePeerDID" command
  pkg/controller/command/didclient/command.go
  pkg/controller/command/didclient/command_test.go
Labels: bug, cla-signed

#191 chore: Update EDV storage provider commit revision
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/main.go
Labels: cla-signed

#192 chore: update to aries 7ec3a2c4697c512726ffaa4143e56491405dd828
  Makefile
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed
