Repository trustbloc/agent-sdk, pull requests merged in 2022-06, with the labels that each got.

#352 chore: update to latest orb vdr
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#341 feat: base implementation for GNAP client in wallet-js-sdk
  cmd/wallet-js-sdk/package-lock.json
  cmd/wallet-js-sdk/package.json
  cmd/wallet-js-sdk/src/gnap/client.js
  cmd/wallet-js-sdk/src/index.js
  cmd/wallet-js-sdk/test/specs/gnap/gnap.spec.js
Labels: cla-signed

#353 chore: update to latest orb vdr
  Makefile
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  cmd/wallet-js-sdk/test/fixtures/.env
  go.mod
  go.sum
Labels: cla-signed

#354 feat: Update EDV dependency
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#365 chore: updated uuid to unblock main
  cmd/wallet-js-sdk/package-lock.json
  cmd/wallet-js-sdk/package.json
  cmd/wallet-js-sdk/src/collection/collections.js
  cmd/wallet-js-sdk/src/did/didmanager.js
  cmd/wallet-js-sdk/src/user/wallet-user.js
  cmd/wallet-js-sdk/src/util/helper.js
  cmd/wallet-js-sdk/test/specs/collection/collection-manager.spec.js
  cmd/wallet-js-sdk/test/specs/common.js
  cmd/wallet-js-sdk/test/specs/credential/credential-manager.spec.js
  cmd/wallet-js-sdk/test/specs/didcomm/didcomm.v1.spec.js
  cmd/wallet-js-sdk/test/specs/didcomm/didcomm.v2.spec.js
  cmd/wallet-js-sdk/test/specs/mocks/adapters.js
  cmd/wallet-js-sdk/test/specs/universal/vcwallet.spec.js
  cmd/wallet-js-sdk/test/specs/user/wallet-user.spec.js
  cmd/wallet-js-sdk/test/specs/util/helper.spec.js
Labels: cla-signed, chore

#366 chore: update latest AFGO revision
  Makefile
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#367 chore: update to latest afgo.
  Makefile
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#370 feat: pass GNAP continue-token value to gnap client.continue()
  cmd/wallet-js-sdk/src/gnap/client.js
  cmd/wallet-js-sdk/test/specs/gnap/gnap.spec.js
Labels: cla-signed

#369 feat: added content-digest header & generation logic for gnap requests
  cmd/wallet-js-sdk/package-lock.json
  cmd/wallet-js-sdk/package.json
  cmd/wallet-js-sdk/src/digest/digest.js
  cmd/wallet-js-sdk/src/gnap/client.js
  cmd/wallet-js-sdk/test/specs/digest/digest.spec.js
Labels: enhancement, cla-signed

#371 feat: add GNAP support
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/main.go
Labels: cla-signed

#372 chore: updated afgo to latest
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  go.mod
  go.sum
Labels: cla-signed

#373 fix: update bootstrap url
  cmd/agent-js-worker/main.go
Labels: cla-signed
