Repository trustbloc/agent-sdk, pull requests merged in 2022-07, with the labels that each got.

#374 feat: initialize webkms for existing user
  cmd/agent-js-worker/main.go
Labels: cla-signed

#381 feat: sign request body in kms gnap header func
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-js-worker/main.go
Labels: cla-signed

#380 feat: http signature module implementation
  cmd/wallet-js-sdk/src/digest/digest.js
  cmd/wallet-js-sdk/src/gnap/client.js
  cmd/wallet-js-sdk/src/httpsig/signer.js
  cmd/wallet-js-sdk/src/index.js
  cmd/wallet-js-sdk/src/util/helper.js
  cmd/wallet-js-sdk/test/specs/digest/digest.spec.js
  cmd/wallet-js-sdk/test/specs/gnap/gnap.spec.js
  cmd/wallet-js-sdk/test/specs/util/helper.spec.js
Labels: enhancement, cla-signed

#385 chore: update afgo
  Makefile
  cmd/agent-js-worker/go.mod
  cmd/agent-js-worker/go.sum
  cmd/agent-mobile/go.mod
  cmd/agent-mobile/go.sum
  cmd/agent-rest/go.mod
  cmd/agent-rest/go.sum
  cmd/wallet-js-sdk/test/fixtures/.env
  cmd/wallet-js-sdk/test/specs/didcomm/connect.v1.spec.js
  go.mod
  go.sum
  pkg/controller/command/didclient/command_test.go
Labels: cla-signed

#383 feat: wasm vcwallet uses httpsig on gnap-authed webkms requests
  cmd/agent-js-worker/main.go
Labels: cla-signed

#387 test: implemented unit tests for http sig module
  cmd/wallet-js-sdk/package-lock.json
  cmd/wallet-js-sdk/package.json
  cmd/wallet-js-sdk/src/httpsig/signer.js
  cmd/wallet-js-sdk/test/specs/httpsig/signer.spec.js
Labels: cla-signed, test

#389 feat: enable edv gnap auth in wasm vcwallet handler
  cmd/agent-js-worker/main.go
Labels: cla-signed

#390 fix: add missing gnap header func (with httpsig) for edv call
  cmd/agent-js-worker/main.go
Labels: cla-signed
