Repository trustbloc/agent-sdk, pull requests merged in 2022-11, with the labels that each got.

#451 test: added more tests for openid4vp initiate api
  cmd/wallet-js-sdk/src/oidc/presentation/openid4vp.js
  cmd/wallet-js-sdk/test/specs/oidc/presentation/openid4vp.spec.js
Labels: cla-signed, test

#453 feat: implemented OIDC presentation submission API
  cmd/wallet-js-sdk/src/oidc/presentation/openid4vp.js
Labels: enhancement, cla-signed

#452 feat: oidc4ci js api
  cmd/wallet-js-sdk/src/index.js
  cmd/wallet-js-sdk/src/oidc/issuance/openid4ci.js
  cmd/wallet-js-sdk/test/specs/oidc/issuance/oidc4ci.spec.js
Labels: cla-signed

#456 test: added unit tests for openid4vp submit api
  cmd/wallet-js-sdk/src/oidc/presentation/openid4vp.js
  cmd/wallet-js-sdk/test/fixtures/testdata/openid4vc-mock-did-doc.json
  cmd/wallet-js-sdk/test/fixtures/testdata/openid4vc-mock-presentation-query.json
  cmd/wallet-js-sdk/test/specs/oidc/presentation/openid4vp.spec.js
Labels: cla-signed, test

#458 fix: updated function params description
  cmd/wallet-js-sdk/docs/wallet_sdk.md
  cmd/wallet-js-sdk/src/oidc/presentation/openid4vp.js
  cmd/wallet-js-sdk/test/specs/oidc/presentation/openid4vp.spec.js
Labels: enhancement, cla-signed

#461 chore: improved mock JWT signer and disabled ES256 signature validation
  cmd/wallet-js-sdk/package-lock.json
  cmd/wallet-js-sdk/package.json
  cmd/wallet-js-sdk/src/oidc/presentation/openid4vp.js
  cmd/wallet-js-sdk/test/fixtures/testdata/openid4vc-mock-did-doc.json
  cmd/wallet-js-sdk/test/specs/oidc/presentation/openid4vp.spec.js
Labels: cla-signed
